services:
  api:
    container_name: blog_api
    hostname: blogapi
    image: blogapi:devlatest
    depends_on:
      - blog_db
    ports:
      - "8080:8080"
    env_file:
      - .env.Docker
    volumes:
      - "./appdata/blog-868a1-credentials.json:/app/blog-868a1-credentials.json"
      - "./appdata/log:/var/log"
    environment:
      GIN_MODE: release
    build:
      context: .
      dockerfile: cmd/blog/Dockerfile
    networks:
      blog_backend:
        aliases:
          - blogapi
  blog_db:
    container_name: blog_db
    hostname: blog_db
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env.Dev
    restart: on-failure
    volumes:
      - ./mongodb:/data/db
    networks:
      - blog_backend
  blog_cache:
    container_name: blog_cache
    hostname: blog_cache
    image: redis:alpine3.20
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    networks:
      - blog_backend

networks:
  blog_backend:
    name: blog_backend
